apiVersion: apps/v1
kind: Deployment
metadata:
  name: huco
  labels:
    app: huco
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: huco
  template:
    metadata:
      labels:
        app: huco
        tier: huco
    spec:
      containers:
      - name: huco
        image: project0620/huco:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: huco
        env:
            - name: "BUCKET_NAME"
              value: huco
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/var/run/secret/cloud.google.com/service-account.json"
          volumeMounts:
            - name: "service-account"
              mountPath: "/var/run/secret/cloud.google.com"
            - name: "certs"
              mountPath: "/etc/ssl/certs"
      volumes:
        - name: "service-account"
          secret:
            secretName: "huco-sa-key"
        - name: "certs"
          hostPath:
            path: "/etc/ssl/certs"
---
apiVersion: v1
kind: Service
metadata:
  name: huco
  labels:
    app: huco
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: huco
    tier: huco
  type: LoadBalancer